name: SSh to my host
on: [push]
jobs:

  build:
    name: SSH to host
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.kino505 }} 
          known_hosts: 'github'
      - name: Deploy with rsync
        run: rsync -avz ./dags/ ${{ secrets.ec2-user }}@prod-parsers.shopfans.io:/tmp/dags/
      - name: executing remote ssh commands
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: "52.204.47.83"
          username: "ec2-user"
          password: "qwerty!!11"
          port: "22"
          script: |
            mkdir -p /tmp/dags
            cd /tmp/dags
            rsync -rtvz ec2-user@52.204.47.83:/tmp/dags/ .
          